
#
# This file is downloaded via the robotpy-sphinx-plugin, and converted
# into a usable sidebar.
#
# This is a downloaded dependency because it's really annoying to make commits
# to all of the projects each time we want to change the sidebar.
#

[projects]
home = "https://amof-docs-home-test.readthedocs.io"
ncas_radar_wind_profiler_1_software = "https://amof-docs-home-test.readthedocs.io/projects/ncas-radar-wind-profiler-1-software"
ncas_aws_10_software = "https://amof-docs-home-test.readthedocs.io/projects/ncas-aws-10-software"


[[toctree]]
name = "Projects"
items = [
    {p="home", k="Documentation Home", v="index"},
    {p="ncas_radar_wind_profiler_1_software", k="ncas-radar-wind-profiler-1-software home", v="index"},
    {p="ncas_aws_10_software", k="ncas-aws-10-software home", v="index"}
]

[[toctree]]
name = "API Reference"
items = [
    {p="ncas_radar_wind_profiler_1_software", k="ncas-radar-wind-profiler-1-software API", v="api"},
    {p="ncas_aws_10_software", k="ncas-aws-10-software API", v="api"}
]
